# Generated by Django 3.2.3 on 2021-05-22 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encurtador', '0002_criacao_url_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urllog',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='urlredirect',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='urlredirect',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
